//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JEMS_Fees_Management_System {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JEMS_Fees_Management_System.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to late_fees.
        /// </summary>
        internal static string st_lf {
            get {
                return ResourceManager.GetString("st_lf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to admission_receipt_start.
        /// </summary>
        internal static string str_ars {
            get {
                return ResourceManager.GetString("str_ars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to belt_tie.
        /// </summary>
        internal static string str_blt {
            get {
                return ResourceManager.GetString("str_blt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to default_warn_fees_date.
        /// </summary>
        internal static string str_dwfd {
            get {
                return ResourceManager.GetString("str_dwfd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ad_form_receipt_start.
        /// </summary>
        internal static string str_frs {
            get {
                return ResourceManager.GetString("str_frs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to monthly_receipt_start.
        /// </summary>
        internal static string str_mrs {
            get {
                return ResourceManager.GetString("str_mrs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to annual_receipt_start.
        /// </summary>
        internal static string str_nrs {
            get {
                return ResourceManager.GetString("str_nrs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to other_receipt_start.
        /// </summary>
        internal static string str_ors {
            get {
                return ResourceManager.GetString("str_ors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to provisional_receipt_start.
        /// </summary>
        internal static string str_prs {
            get {
                return ResourceManager.GetString("str_prs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to session.
        /// </summary>
        internal static string str_ssn {
            get {
                return ResourceManager.GetString("str_ssn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to warn_fees.
        /// </summary>
        internal static string str_wf {
            get {
                return ResourceManager.GetString("str_wf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to warn_fees_date.
        /// </summary>
        internal static string str_wfd {
            get {
                return ResourceManager.GetString("str_wfd", resourceCulture);
            }
        }
    }
}
